/**
 * Comprehensive ISO 80369-7 & ISO 80369-20 Bilingual (EN/ZH) Knowledge Base Helper
 * Guarantees zero blindspots in English mode across all tabs, cards, modals, and figures.
 */

export interface TopicI18nData {
  shortSummaryEn: string;
  detailedDescriptionEn: string;
  engineeringRiskEn: string;
  auditFocusEn: string;
}

export interface ClauseI18nData {
  titleEn?: string;
  objectiveEn: string;
  appliesToEn: string;
  typeEn: string;
  fixtureRequiredEn?: string;
  regulatoryTipEn?: string;
  preAssemblyDescEn?: string;
}

export interface FigureI18nData {
  worstCaseReasonEn: string;
  descriptionEn: string;
}

export const TOPIC_I18N: Record<string, TopicI18nData> = {
  'fluid-leakage': {
    shortSummaryEn: 'Evaluates sealing integrity of 6% Luer taper and threads under 300-330 kPa positive pressure (Water method: no falling drop / Air decay: leak rate <= 0.005 Pa·m3/s).',
    detailedDescriptionEn: 'Positive pressure fluid leakage testing is the fundamental cornerstone of medical Luer connector verification. After assembling to a standard metal reference fixture at mandated assembly torque (0.08 to 0.12 N·m), test connectors are evaluated under 300 kPa to 330 kPa hydraulic or pneumatic pressure. Under the Pressure Decay Method (Annex B), pressure is maintained for 15-20 s with a maximum allowable leak rate of 0.005 Pa·m3/s. Per ISO 80369-20:2024 revision, the formula for leak rate Q has been retired in favor of directly recording differential pressure change (Delta P), calculated via Delta P_max = (Q_max * Delta t) / V. Under the Falling Drop Method (Annex C), pressure is held for 30-35 s with zero liquid drop formation or release allowed.',
    engineeringRiskEn: 'Insufficient surface roughness on the 6% taper (Ra > 0.8 um), micro-flash along the mold parting line, or part ovality from uneven mold shrinkage will compromise cone seal lines and cause immediate leakage under 300 kPa pressure.',
    auditFocusEn: 'Inspect pre-test conditioning documentation (23 +/- 2 deg C, 50 +/- 5% RH, >= 24 h). For pressure decay, audit whether test system internal volume V was calibrated per ISO 80369-20:2024 Figure B.1 and disclosed in Section .5.'
  },
  'sub-atmospheric-air-leakage': {
    shortSummaryEn: 'Evaluates air leakage under 80.0 to 88.0 kPa vacuum negative pressure (Annex D dry vacuum decay or Annex K wet aspiration bubbling).',
    detailedDescriptionEn: 'Sub-atmospheric pressure testing simulates clinical blood aspiration, vacuum tube blood collection, or infusion syringe pull-back. Under vacuum conditions, ambient atmospheric pressure compresses the connector from outside-in while internal negative pressure tends to draw air through micro-voids in the sealing taper. Evaluated under Annex D (vacuum decay method: 80.0 to 88.0 kPa vacuum held for 15-20 s, decay rate <= 0.005 Pa·m3/s) or Annex K (water submersion aspiration: visually inspect for continuous bubble stream over 15-20 s).',
    engineeringRiskEn: 'Plastic material creep relaxation or taper taper mismatch under negative pressure can suck air across the interface, resulting in fatal clinical air embolism during intravenous procedures.',
    auditFocusEn: 'Review laboratory calibration certificate for negative pressure sensors and verify vacuum line rigid tubing selection to prevent flexible tubing collapse from invalidating volume measurements.'
  },
  'overriding-torque': {
    shortSummaryEn: 'Applies 0.15 to 0.17 N·m destructive over-torque with Figure C.3 worst-case 2.71 mm narrow lug fixture to evaluate collar hoop expansion resistance.',
    detailedDescriptionEn: 'Clinical practitioners frequently over-tighten Luer connectors during emergency or intensive care procedures. Overriding resistance verification subjects assembled connectors to 0.15 to 0.17 N·m over-torque (1.5x standard assembly torque) for 5 to 10 s. Threads and lugs must not override, strip, or structurally crack. The standard mandatorily pairs male connectors with Figure C.3 (2.71 mm narrowed lug) worst-case metal fixtures.',
    engineeringRiskEn: 'Low material flexural modulus (e.g. unmodified polypropylene < 1200 MPa) allows collar dilation under hoop stress generated by thread flank incline, causing the 2.71 mm narrow lug to slip over thread crests.',
    auditFocusEn: 'Verify whether Figure C.3 reference connector was utilized and inspect dimensional inspection records of lug width (2.71 +/- 0.02 mm) and back flank angle (30 deg +/- 1 deg).'
  },
  'axial-separation': {
    shortSummaryEn: 'Applies 23-25 N (Slip) or 32-35 N (Lock) axial pull force for 10-15 s to ensure no separation from reference fixture.',
    detailedDescriptionEn: 'Simulates tensile tension exerted by infusion line tugging or patient posture shifts. Evaluates connector retention strength following standard pre-assembly (0.08 to 0.12 N·m torque + 26.5 to 27.5 N axial push held for 5-6 s). Slip connectors undergo 23-25 N axial pull; Lock connectors undergo 32-35 N axial pull at 10 N/s ramp rate, held for 10-15 s.',
    engineeringRiskEn: 'Inadequate collar thread root radius generates excessive stress concentration, leading to catastrophic thread shear fracture under 32 to 35 N axial pull on lock connectors.',
    auditFocusEn: 'Verify pull rate (<= 10 N/s) on universal testing machine and verify zero axial separation displacement.'
  },
  'unscrewing-separation': {
    shortSummaryEn: 'Applies 0.018 to 0.020 N·m reverse unscrewing torque for 10-15 s to verify self-locking retention.',
    detailedDescriptionEn: 'Evaluates anti-loosening security of threaded Luer connections subjected to patient movement and tubing torsional resonance. After standard assembly, a reverse unscrewing torque of 0.018 to 0.020 N·m is applied for 10 to 15 s. The male and female connectors must remain fully engaged without backing off.',
    engineeringRiskEn: 'Excessive taper lubricity (e.g. silicone oil migration) or sub-standard thread friction coefficients will cause spontaneous unscrewing and dislodgement under minor vibration.',
    auditFocusEn: 'Examine torque gauge sensitivity in low-torque range (0.001 N·m resolution) and ensure torque application direction is strictly perpendicular to connector axis.'
  },
  'stress-cracking': {
    shortSummaryEn: 'Assembles connectors to reference fixtures and conditions in air at 15 to 30 deg C (recommended 23 deg C) for 48 h (Annex E) to evaluate mechanical stress cracking.',
    detailedDescriptionEn: 'Evaluates sustained assembly hoop stress and creep resistance of polymer materials following assembly. Medical plastic Luer components experience high residual hoop stresses when assembled to rigid metal reference fixtures. Under ISO 80369-20 Annex E, specimens are held assembled at 15 to 30 deg C (recommended 23 +/- 2 deg C) for >= 48 h in air, then subjected to Clause 6.1.1 positive-pressure fluid leakage testing.',
    engineeringRiskEn: 'Amorphous polymers (e.g. polycarbonate, acrylic) without proper annealing or design are susceptible to stress cracking under sustained assembly hoop strain.',
    auditFocusEn: 'Inspect chamber temperature log (15 to 30 deg C / 23 +/- 2 deg C continuously for 48 h) and review post-conditioning Clause 6.1.1 leakage pass/fail verification data.'
  },
  'dimensional-taper': {
    shortSummaryEn: 'Inspects 6% (1:16.667) Luer taper geometry, socket depth, thread pitch, and lug envelope dimensions per Annex B drawings.',
    detailedDescriptionEn: 'Normative geometric foundation of ISO 80369-7. Mandates 6% taper ratio (taper angle 1 deg 43 min 9 sec), cone outer diameter, socket inner diameter, thread pitch (2.5 mm), and lug profiles across Figures B.1 through B.6. Connectors meeting dimensional tolerances ensure universal interchangeability with all conforming Luer medical devices worldwide.',
    engineeringRiskEn: 'Dimensional drift from injection mold wear or thermal shrinkage variance causes taper angle mismatch, leading to point-contact sealing rather than full-surface taper sealing.',
    auditFocusEn: 'Verify CMM measurement uncertainty and calibration traceability for taper angle, cone diameter at reference line, and thread pitch.'
  },
  'reference-connectors': {
    shortSummaryEn: 'Provides hardened stainless steel reference connectors (Figures C.1-C.6) and calibration criteria (Ra <= 0.8 um, hardened to resist wear).',
    detailedDescriptionEn: 'Defines standard reference connectors manufactured from hardened stainless steel (elastic modulus > 3,433 MPa, hardened to resist wear, surface roughness Ra <= 0.8 um) to serve as invariant counter-fixtures during compliance testing. Includes nominal connectors (C.1, C.2, C.4, C.5) and worst-case mechanical testing fixtures (C.3 with 2.71 mm narrow lug, C.6 with 2.71 mm narrow male threads).',
    engineeringRiskEn: 'Using unhardened soft stainless steel (e.g. annealed 316) causes galling and premature wear during repeated torque testing, altering test outcomes.',
    auditFocusEn: 'Audit fixture calibration certificates: verify hardness (>= 45 HRC for hardened grades), roughness Ra <= 0.8 um on sealing surfaces, and critical dimensions.'
  },
  'pre-assembly': {
    shortSummaryEn: 'Standard pre-assembly procedure: simultaneously apply 0.08-0.12 N·m torque and 26.5-27.5 N axial push for 5-6 s, then release.',
    detailedDescriptionEn: 'Per ISO 80369-20 Annex H.4 a) and Clause 5, standard pre-assembly requires simultaneous application of 0.08 to 0.12 N·m tightening torque and 26.5 to 27.5 N axial force, held for 5 to 6 s before load release. This procedure seats the 6% tapers uniformly and establishes consistent friction and preload prior to test challenge execution.',
    engineeringRiskEn: 'Failure to simultaneously apply torque and axial force results in improper taper seating, causing variable and unrepeatable test results.',
    auditFocusEn: 'Verify automated dual-axis pre-assembly apparatus calibration and ensure pre-assembly hold time was maintained strictly between 5 and 6 seconds.'
  },
  'non-interchangeability': {
    shortSummaryEn: 'Enforces cross-discipline lockout matrices to prevent dangerous misconnections between vascular, enteral, neuraxial, and breathing systems.',
    detailedDescriptionEn: 'The core mission of the ISO 80369 standard series is preventing catastrophic medical tubing misconnections. ISO 80369-7 governs vascular/subcutaneous Luer connectors, which are physically and geometrically locked out from enteral (ISO 80369-3 ENFit), breathing (ISO 80369-2), and neuraxial (ISO 80369-6 NRFit) connectors via CAD envelope analysis and forced physical mating tests.',
    engineeringRiskEn: 'Luer fittings on non-vascular medical devices risk wrongful administration of enteral nutrition or anesthetic agents directly into intravascular lines.',
    auditFocusEn: 'Audit CAD 3D envelope interference simulation reports and verify non-interchangeability evaluation per ISO 80369-1 Annex B.'
  },
  'scope-normative-terms': {
    shortSummaryEn: 'Governs scope of application (intravascular/subcutaneous), referenced standard frameworks, and normative terminology definitions.',
    detailedDescriptionEn: 'Defines scope of ISO 80369-7: small-bore connectors intended for use in intravascular or subcutaneous applications of medical devices and accessories. Establishes normative references (ISO 80369-1, ISO 80369-20, ISO 14971) and terminology definitions (Luer connector, Luer lock, Luer slip, reference connector).',
    engineeringRiskEn: 'Misinterpreting scope limits or applying Luer fittings to excluded applications (e.g. enteral or breathing) violates international regulatory mandates.',
    auditFocusEn: 'Verify device intended use classification aligned with ISO 80369-7 scope in technical documentation and DVP design history files.'
  },
  'statistical-analysis-annex-j': {
    shortSummaryEn: 'Calculates upper/lower tolerance limits (UTL/LTL) using variable test data per Annex J to demonstrate 95% confidence and 95% conformance.',
    detailedDescriptionEn: 'Annex J provides statistical methods for evaluating variable test data (e.g. leakage rates, burst pressures, separation forces). Demonstrating compliance requires proving with 95% confidence that >= 95% of manufactured parts meet acceptance criteria, using the non-central t-distribution tolerance factor k.',
    engineeringRiskEn: 'Relying solely on sample mean without accounting for standard deviation and tolerance intervals risks shipping out-of-spec outlier products.',
    auditFocusEn: 'Audit sample size rationale (n >= 10, typically n = 30 for 95/95), normality test verification (Anderson-Darling or Shapiro-Wilk), and k-factor computation.'
  },
  'annexes-rationale-summary': {
    shortSummaryEn: 'Summarizes ISO standard rationale, design history, clinical justification for test limits, and ISO 80369-20:2024 revision updates.',
    detailedDescriptionEn: 'Synthesizes clinical and engineering justifications behind ISO 80369-7 requirements. Details why 300–330 kPa was selected as the pressure limit (covering clinical infusion pump maximum operating pressures), why 32–35 N (Lock) and 23–25 N (Slip) represent clinical pulling resistance, and documents the transition from legacy ISO 594-1/2 to ISO 80369-7 and ISO 80369-20:2024.',
    engineeringRiskEn: 'Designing connectors without understanding clinical force limits leads to over-designed bulky fittings or under-designed prone-to-failure products.',
    auditFocusEn: 'Ensure risk management files (ISO 14971) cite ISO 80369-7 Annex rationales when establishing clinical hazard mitigations.'
  }
};

export const CLAUSE_I18N: Record<string, ClauseI18nData> = {
  'iso7-6.1': {
    titleEn: 'Fluid Leakage by Pressure',
    objectiveEn: 'Verify that assembled Luer connectors exhibit no liquid leakage under 300-330 kPa positive pressure (Falling drop: no drop in 30-35 s / Pressure decay: rate <= 0.005 Pa·m3/s in 15-20 s).',
    appliesToEn: 'Male & female Luer lock and slip connectors (vascular & subcutaneous)',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.1 (Female Lock) / Fig.C.2 (Male Slip) / Fig.C.4 (Male Lock) / Fig.C.5 (Female Slip)',
    regulatoryTipEn: 'Mandatory core test for FDA 510(k) and CE MDR submissions. Disclose test medium (water or air) and pressure decay system volume V.'
  },
  'iso7-6.2': {
    titleEn: 'Sub-atmospheric Air Leakage',
    objectiveEn: 'Verify that assembled Luer connectors prevent air ingress under 80.0 to 88.0 kPa vacuum negative pressure (Annex D vacuum decay or Annex K aspiration).',
    appliesToEn: 'Male & female Luer lock and slip connectors',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.1 / Fig.C.2 / Fig.C.4 / Fig.C.5 standard reference fixtures',
    regulatoryTipEn: 'Critical for blood line access and syringe infusion sets to prevent clinical air embolism.'
  },
  'iso7-6.3': {
    titleEn: 'Stress Cracking',
    objectiveEn: 'Verify that connectors assembled to reference fixtures do not exhibit micro-cracking after 48 h room temperature conditioning, and subsequently pass Clause 6.1 leakage test.',
    appliesToEn: 'Male & female Luer lock and slip connectors made of polymer materials',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.1 / Fig.C.2 / Fig.C.4 / Fig.C.5',
    regulatoryTipEn: 'Pay special attention to molded residual hoop stresses in polycarbonate and acrylic transparent luer fittings.'
  },
  'iso7-6.4': {
    titleEn: 'Resistance to Separation from Axial Load',
    objectiveEn: 'Verify that assembled connectors remain joined without separation under 23-25 N (Slip) or 32-35 N (Lock) axial pull force held for 10-15 s.',
    appliesToEn: 'Male & female Luer lock and slip connectors',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.3 (Male Lock worst-case) / Fig.C.6 (Female Lock worst-case) / Fig.C.2 / Fig.C.5',
    regulatoryTipEn: 'For male lock connectors, testing MUST pair with Fig.C.3 (2.71 mm narrow lug worst-case fixture).'
  },
  'iso7-6.5': {
    titleEn: 'Resistance to Separation from Unscrewing',
    objectiveEn: 'Verify that threaded Luer lock connections remain locked without unscrewing when subjected to 0.018 to 0.020 N·m reverse torque for 10-15 s.',
    appliesToEn: 'Male & female Luer lock connectors only',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.1 (Female Lock) / Fig.C.4 (Male Lock)',
    regulatoryTipEn: 'Validates self-locking taper friction to avoid spontaneous disconnection under patient movements.'
  },
  'iso7-6.6': {
    titleEn: 'Resistance to Overriding',
    objectiveEn: 'Verify that Luer lock threads and lugs do not strip, override, or cock under 0.15 to 0.17 N·m destructive over-torque held for 5-10 s.',
    appliesToEn: 'Male & female Luer lock connectors only',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Fig.C.3 (Female 2.71 mm narrow lug worst-case fixture)',
    regulatoryTipEn: 'Standard strictly mandates pre-assembly (0.08-0.12 N·m + 27.5 N push for 5-6 s) prior to applying 0.17 N·m overriding torque. Over-tightening directly is non-compliant deviation.'
  },
  'iso7-clause-4': {
    titleEn: 'General Requirements & Non-Interchangeability',
    objectiveEn: 'Ensure dimensional and mechanical lockout preventing misconnection with other medical small-bore connectors (ISO 80369-1).',
    appliesToEn: 'All ISO 80369-7 Luer connectors',
    typeEn: 'General Principle',
    fixtureRequiredEn: 'Non-interchangeability test fixtures per ISO 80369-1',
    regulatoryTipEn: 'Document compliance in risk management file per ISO 14971.'
  },
  'iso7-clause-5.1': {
    titleEn: 'Dimensional Requirements',
    objectiveEn: 'Verify that connector dimensions conform fully to Annex B engineering drawings (Fig.B.1 to B.6).',
    appliesToEn: 'All Luer connectors',
    typeEn: 'Specification Clause',
    fixtureRequiredEn: 'Precision CMM / optical vision measuring machine',
    regulatoryTipEn: 'Include complete dimensional inspection report (FAIR) in regulatory technical dossier.'
  },
  'iso20-annex-b': {
    titleEn: 'Annex B - Pressure Decay Positive Pressure Leakage Test Method',
    objectiveEn: 'Standard procedure for quantitative positive pressure leakage testing via pneumatic pressure decay (Delta P).',
    appliesToEn: 'All medical small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'ISO 80369-7 Annex C reference connectors',
    regulatoryTipEn: 'ISO 80369-20:2024 mandates disclosing system internal test volume V.'
  },
  'iso20-annex-c': {
    titleEn: 'Annex C - Falling Drop Positive Pressure Liquid Leakage Test Method',
    objectiveEn: 'Standard procedure for qualitative hydraulic leakage testing via falling water drop observation.',
    appliesToEn: 'All medical small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Annex C reference connectors with water supply',
    regulatoryTipEn: 'Ensure complete de-aeration of test circuit prior to 30 s pressure hold.'
  },
  'iso20-annex-d': {
    titleEn: 'Annex D - Sub-atmospheric Air Leakage Test Method (Vacuum Decay)',
    objectiveEn: 'Quantitative vacuum decay test method applying 80.0 to 88.0 kPa negative pressure.',
    appliesToEn: 'All small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Vacuum manifold and Annex C reference fixtures',
    regulatoryTipEn: 'Calibrate vacuum sensor within valid calibration interval.'
  },
  'iso20-annex-e': {
    titleEn: 'Annex E - Stress Cracking Test Method',
    objectiveEn: 'Standard environmental conditioning method: 48 h assembly hold at 23 deg C prior to leakage testing.',
    appliesToEn: 'Polymer small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Annex C hardened metal reference fixtures',
    regulatoryTipEn: 'Environmental chamber log must demonstrate uninterrupted 23 +/- 2 deg C temperature control.'
  },
  'iso20-annex-f': {
    titleEn: 'Annex F - Resistance to Separation from Axial Load Test Method',
    objectiveEn: 'Tensile test procedure applying axial pull force at <= 10 N/s rate up to designated load.',
    appliesToEn: 'All small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Universal testing machine with axial alignment grips',
    regulatoryTipEn: 'Inspect tensile load cell calibration and alignment verification records.'
  },
  'iso20-annex-g': {
    titleEn: 'Annex G - Resistance to Separation from Unscrewing Test Method',
    objectiveEn: 'Torsional test procedure applying reverse unscrewing torque of 0.020 N·m for 10-15 s.',
    appliesToEn: 'Threaded small-bore connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Calibrated low-torque testing instrument',
    regulatoryTipEn: 'Verify low-range torque resolution (<= 0.001 N·m).'
  },
  'iso20-annex-h': {
    titleEn: 'Annex H - Resistance to Overriding Test Method',
    objectiveEn: 'Destructive torsional test procedure applying 0.15-0.17 N·m torque following mandatory pre-assembly.',
    appliesToEn: 'Threaded lock connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Figure C.3 (Female worst-case 2.71 mm lug) fixture',
    regulatoryTipEn: 'Document both pre-assembly conditions and final destructive torque hold parameters.'
  },
  'iso20-annex-j': {
    titleEn: 'Annex J - Statistical Variability Analysis Method',
    objectiveEn: 'Calculates upper/lower tolerance limits (UTL/LTL) from variable data for 95/95 compliance.',
    appliesToEn: 'Variable test data across all Annexes',
    typeEn: 'General Principle',
    fixtureRequiredEn: 'Statistical computation software / worksheets',
    regulatoryTipEn: 'FDA reviewers expect sample size justification and normality verification.'
  },
  'iso20-annex-k': {
    titleEn: 'Annex K - Sub-atmospheric Air Leakage During Aspiration Test Method',
    objectiveEn: 'Submersion aspiration test method inspecting for continuous air bubble streams.',
    appliesToEn: 'Syringes, aspirating catheters, blood collection sets',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Water bath viewing chamber with vacuum aspiration source',
    regulatoryTipEn: 'Ensure illuminated magnification is provided for bubble identification.'
  },
  'iso7-annex-a': {
    titleEn: 'Rationale and Guidance',
    objectiveEn: 'Details the clinical and scientific rationale for key test parameters: 300–330 kPa pressure, 32–35 N / 23–25 N axial pull force, and 0.15–0.17 N·m torque limits.',
    appliesToEn: 'R&D design validation and risk management documentation',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Technical background documentation',
    regulatoryTipEn: 'Best reference when preparing ISO 14971 risk analysis reports to justify safety margins to notified bodies.'
  },
  'iso7-annex-b': {
    titleEn: 'Dimensional Drawings for Luer Connectors',
    objectiveEn: 'Provides complete CAD dimensions and tolerance matrices for male and female Luer lock and slip connectors (Fig.B.1 to B.6).',
    appliesToEn: 'Mold design and production full-dimensional inspection',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'CMM and optical projector / vision measuring system',
    regulatoryTipEn: 'Full 2D dimensional annotation and 3D envelope drawing required as 510(k) / CE MDR attachment.'
  },
  'iso7-annex-c': {
    titleEn: 'Reference Connectors (Fig.C.1 to C.6)',
    objectiveEn: 'Provides precise 3D geometry and material specifications for 6 standardized hardened stainless steel reference connectors as the globally unified test basis.',
    appliesToEn: 'All ISO 80369-7 physical and mechanical performance tests',
    typeEn: 'Reference Fixture',
    fixtureRequiredEn: 'C.1 (Female Lock Nominal 3.50mm), C.2 (Male Slip), C.3 (Female Worst-case 2.71mm), C.4 (Male Lock), C.5 (Female Slip), C.6 (Male Worst-case)',
    regulatoryTipEn: 'FDA 510(k) reviews commonly require calibration certificates and dimensional traceability records for reference connectors.'
  },
  'iso7-annex-d': {
    titleEn: 'Assessment of Non-interchangeability',
    objectiveEn: 'Specifies 3D CAD envelope simulation and physical forced-mating tests to verify non-interchangeability with other medical small-bore connector families.',
    appliesToEn: 'Novel and derivative small-bore connector designs',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'CAD collision analysis software and physical interference test fixture',
    regulatoryTipEn: 'Non-interchangeability test report is a mandatory focus item for FDA 510(k) and TFDA regulatory reviews.'
  },
  'iso7-annex-e': {
    titleEn: 'Summary of Testing Requirements',
    objectiveEn: 'Provides a summary matrix of all required test clauses for each connector gender (male/female) and type (lock/slip).',
    appliesToEn: 'DVP&R test plan design',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Test plan matrix / DVP&R document',
    regulatoryTipEn: 'Core reference table when drafting DVP&R test plans — ensure full clause coverage per connector type.'
  },
  'iso7-clause-5': {
    titleEn: 'Dimensional Requirements for Luer Connectors',
    objectiveEn: 'Precisely specifies the 6% taper (1:16.667), engagement length (≥7.5 mm), and thread pitch for male and female Luer connectors to ensure global interoperability.',
    appliesToEn: 'All ISO 80369-7 Luer lock and slip connectors',
    typeEn: 'Specification Clause',
    fixtureRequiredEn: 'CMM, optical projector, and standard ring/plug gauges',
    regulatoryTipEn: 'FDA 510(k) review requires a Full Dimensional Inspection Report (FAIR) referencing Fig.B.1–B.6 tolerances.'
  },
  'iso20-clause-1': {
    titleEn: 'Scope of Common Test Methods',
    objectiveEn: 'Defines the scope of common laboratory test methods applicable to all ISO 80369 series small-bore connectors.',
    appliesToEn: 'ISO 80369-2, -3, -5, -6, -7 all application domains',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'ISO 17025 accredited laboratory quality system',
    regulatoryTipEn: 'Laboratory ISO 17025 accreditation is expected for regulatory submissions to FDA, CE MDR, and TFDA.'
  },
  'iso20-clause-2': {
    titleEn: 'Normative References',
    objectiveEn: 'Lists fundamental measurement and metrology standards required for instrument calibration and traceability in laboratory test execution.',
    appliesToEn: 'Laboratory instrument calibration and environmental control',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Instrument calibration certificates with national standard traceability',
    regulatoryTipEn: 'Calibration reports with national standard traceability must be attached during regulatory audits.'
  },
  'iso20-clause-3': {
    titleEn: 'Terms and Definitions',
    objectiveEn: 'Defines key testing terminology: Test sample, Assembly, Leak rate, Pre-assembly, and other standard-specific terms used throughout ISO 80369-20.',
    appliesToEn: 'Laboratory test reports and data records',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Test report terminology review checklist',
    regulatoryTipEn: 'Consistent and unambiguous nomenclature is the foundation of regulatory report quality and audit compliance.'
  },
  'iso20-clause-4': {
    titleEn: 'General Requirements & Test Conditions',
    objectiveEn: 'Specifies mandatory preconditioning (20±5°C, 50±10% RH, ≥24 h) and fixture requirements applicable to all ISO 80369-20 annex test methods.',
    appliesToEn: 'All ISO 80369-20 annex test methods',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Temperature and humidity controlled conditioning chamber',
    regulatoryTipEn: 'Preconditioning of hygroscopic materials (e.g. Nylon PA) is a mandatory regulatory audit focus item.'
  },
  'iso20-annex-a': {
    titleEn: 'Test Methods for Dimensional Attributes',
    objectiveEn: 'Specifies standard measurement conditions for verifying geometric dimensions using gauges (Go/No-Go) and precision coordinate measuring equipment.',
    appliesToEn: 'All ISO 80369 series connectors',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Go/No-Go gauges, CMM, or optical vision measuring system at 20±2°C metrology room',
    regulatoryTipEn: 'Dimensional measurement reports must reference calibrated equipment and comply with GD&T per ISO 14405.'
  },
  'iso20-annex-i': {
    titleEn: 'Disconnection by Unscrewing Test Method',
    objectiveEn: 'Evaluates the maximum peak disconnection torque when unscrewing and separating the connector, ensuring clinical ease of disconnection for healthcare workers.',
    appliesToEn: 'Luer lock connectors requiring frequent manual disconnection',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Fig.C.1 (Female Lock) or Fig.C.4 (Male Lock) reference connector; calibrated low-torque instrument',
    regulatoryTipEn: 'Key metric for Human Factors Engineering (Usability Engineering per IEC 62366) evaluation and FDA submission.'
  },
  'iso7-clause-1': {
    titleEn: 'Scope of ISO 80369-7',
    objectiveEn: 'Defines that ISO 80369-7 applies to small-bore Luer connectors used in intravascular or subcutaneous medical applications.',
    appliesToEn: 'All IV infusion lines, syringes, indwelling needles, stopcocks, and catheter connector interfaces',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Regulatory applicability review checklist',
    regulatoryTipEn: 'First step for 510(k)/CE submissions: confirm regulatory classification and scope of applicable standard.'
  },
  'iso7-clause-2': {
    titleEn: 'Normative References',
    objectiveEn: 'Lists indispensable normative references for ISO 80369-7 testing: ISO 80369-1 (general non-interchangeability) and ISO 80369-20 (common test methods).',
    appliesToEn: 'ISO 80369-1 and ISO 80369-20 current editions',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Standards traceability records',
    regulatoryTipEn: 'FDA and EU MDR now mandate full transition to ISO 80369 series; citing superseded ISO 594 is non-compliant.'
  },
  'iso7-clause-3': {
    titleEn: 'Terms and Definitions',
    objectiveEn: 'Precisely defines core terminology: Luer connector, Luer slip, Luer lock, reference connector, leak rate, and other standard-specific terms.',
    appliesToEn: 'All Luer connector technical documents and engineering drawings',
    typeEn: 'Requirement',
    fixtureRequiredEn: 'Specification document review',
    regulatoryTipEn: 'Align DHF (Design History File) nomenclature table with Clause 3 definitions to prevent regulatory RFIs.'
  },
  'iso20-general-procedure': {
    titleEn: 'Standard Pre-assembly Method Across All Annexes',
    objectiveEn: 'Standardizes the pre-assembly torque and axial push force procedure required before all Annex B–I performance tests.',
    appliesToEn: 'All ISO 80369-20 performance test annexes',
    typeEn: 'Test Method',
    fixtureRequiredEn: 'Calibrated automatic torque driver and spring axial force mechanism',
    regulatoryTipEn: 'Automated torque test systems must include real-time assembly force curve records for regulatory submissions.'
  }
};

export const FIGURE_I18N: Record<string, FigureI18nData> = {
  'A.1': {
    worstCaseReasonEn: 'Establishes normative cross-discipline physical lockout baseline, ensuring medical small-bore connectors from different clinical domains cannot misconnect.',
    descriptionEn: 'ISO 80369 Family non-interchangeability geometry matrix: vascular (Luer -7), enteral (ENFit -3), neuraxial (NRFit -6), and breathing (-2) isolation architecture.'
  },
  'B.1': {
    worstCaseReasonEn: 'Standard male Luer slip connector (L1), intended for non-threaded sliding engagement.',
    descriptionEn: '6% (1:16.667) male Luer slip connector CAD dimensional drawing: cone length e >= 7.5 mm, small-end diameter Od 3.970-4.035 mm, large-end diameter Og 4.375-4.440 mm, and taper slope.'
  },
  'B.2': {
    worstCaseReasonEn: 'Standard female Luer slip connector (L1), intended for receiving male slip cone.',
    descriptionEn: '6% female Luer slip connector CAD dimensional drawing: major ID OD 4.225-4.270 mm, minor ID OG 3.820-3.865 mm, and internal socket angle.'
  },
  'B.3': {
    worstCaseReasonEn: 'Equipped with standard rigid collar and internal threads, providing robust locking interface with female lugs.',
    descriptionEn: 'Male Luer lock connector with rigid internal thread collar CAD drawing: thread pitch = 2.5 mm, 25 deg thread profile, crest position t <= 3.2 mm, and projection c >= 2.1 mm.'
  },
  'B.4': {
    worstCaseReasonEn: 'Features rotatable collar for flexible clinical line positioning while preventing line kink.',
    descriptionEn: 'Male Luer lock connector with rotatable thread collar CAD drawing: specifies swivel clearance, retaining groove, and axial play limits.'
  },
  'B.5': {
    worstCaseReasonEn: 'Alternative design incorporating external collar with internal threads for syringe tips and stopcocks.',
    descriptionEn: 'Male Luer lock connector with external collar CAD drawing: specifies thread dimensions, collar outer diameter, and engagement depth.'
  },
  'B.6': {
    worstCaseReasonEn: 'Standard female Luer lock connector (L2) with dual symmetric lugs for secure thread engagement.',
    descriptionEn: 'Female Luer lock connector with threaded lugs CAD drawing: specifies lug width 3.50 mm, lead chamfers, and external envelope.'
  },
  'B.7': {
    worstCaseReasonEn: 'Female Luer lock connector variant B with right-angled lugs, common in injection-molded components.',
    descriptionEn: 'Female Luer lock connector with right-angled lugs CAD drawing: specifies right-angle profile, radius, and lug width.'
  },
  'B.8': {
    worstCaseReasonEn: 'Female Luer lock connector variant C with extended lugs for high-torque manual handling.',
    descriptionEn: 'Female Luer lock connector variant C CAD drawing: specifies extended profile, grip tabs, and dimensional envelope.'
  },
  'C.1': {
    worstCaseReasonEn: 'Nominal female Luer lock reference connector (3.50 mm lug width, Ra <= 0.8 um) for standard leakage and durability testing.',
    descriptionEn: 'Female Luer lock metal reference connector (Nominal, Fig.C.1): hardened stainless steel, 3.50 mm lug width, Ra <= 0.8 um, used for 6.1 leakage and 6.5 unscrewing tests.'
  },
  'C.2': {
    worstCaseReasonEn: 'Nominal male Luer slip reference connector for evaluating female slip connectors.',
    descriptionEn: 'Male Luer slip metal reference connector (Nominal, Fig.C.2): hardened stainless steel, 6% precision ground taper, used for testing female slip components.'
  },
  'C.3': {
    worstCaseReasonEn: 'Mandated worst-case female reference connector (narrowed 2.71 mm lug width, 30 deg flank angle). Severe stress concentration tests hoop expansion and shear resistance under 6.4 pull and 6.6 overriding!',
    descriptionEn: 'Worst-case female reference connector (Fig.C.3): narrowed 2.71 mm lug width (-22% area), 30 deg back flank angle. Mandated for Clause 6.4 axial separation and Clause 6.6 overriding torque tests.'
  },
  'C.4': {
    worstCaseReasonEn: 'Nominal male Luer lock reference connector for evaluating female lock connectors under standard conditions.',
    descriptionEn: 'Male Luer lock metal reference connector (Nominal, Fig.C.4): precision internal threads and 6% male cone, used for testing female lock connectors.'
  },
  'C.5': {
    worstCaseReasonEn: 'Nominal female Luer slip reference connector for evaluating male slip connectors.',
    descriptionEn: 'Female Luer slip metal reference connector (Nominal, Fig.C.5): precision internal socket, Ra <= 0.8 um, used for testing male slip connectors.'
  },
  'C.6': {
    worstCaseReasonEn: 'Mandated worst-case male Luer lock reference connector with minimized thread engagement profile for mechanical testing of female connectors.',
    descriptionEn: 'Worst-case male Luer lock reference connector (Fig.C.6): hardened stainless steel, minimized thread profile, mandated for testing female Luer lock mechanical retention.'
  },
  'SML': {
    worstCaseReasonEn: 'Small-volume Luer connector profile used in ophthalmic, pediatric, and low-dead-space syringes.',
    descriptionEn: 'Small-volume Luer connector profile CAD drawing: minimizes internal residual dead volume while preserving 6% taper seal.'
  },
  'ISO20-B.1': {
    worstCaseReasonEn: 'Standard laboratory test rig schematic for positive pressure decay testing.',
    descriptionEn: 'ISO 80369-20 Figure B.1: Testing apparatus layout for pressure decay positive pressure leakage method, including air source, shut-off valve, precision transducer, and test volume.'
  },
  'ISO20-B.2': {
    worstCaseReasonEn: 'Pressure decay test curve stages: Charge -> Settle (Thermal equalization) -> Measure (15-20 s) -> Exhaust.',
    descriptionEn: 'ISO 80369-20 Annex B.4 pressure decay process curve diagram: illustrates pressurization, stabilization, differential pressure measurement (Delta P), and exhaust cycle.'
  },
  'ISO20-C.1': {
    worstCaseReasonEn: 'Standard laboratory test apparatus layout for positive pressure liquid leakage testing.',
    descriptionEn: 'ISO 80369-20 Figure C.1: Falling drop liquid leakage test apparatus layout, showing water reservoir, de-aeration chamber, pressure regulator, and observation plate.'
  },
  'ISO20-D.1': {
    worstCaseReasonEn: 'Standard vacuum decay test apparatus schematic.',
    descriptionEn: 'ISO 80369-20 Figure D.1: Testing apparatus layout for sub-atmospheric air leakage under vacuum decay, showing vacuum pump, shut-off valve, and negative pressure transducer.'
  },
  'ISO20-E.1': {
    worstCaseReasonEn: 'Stress cracking test setup schematic.',
    descriptionEn: 'ISO 80369-20 Annex E stress cracking test procedure schematic: assembled connector conditioning in air at 15 to 30 deg C (recommended 23 deg C) for >= 48 h, followed by Clause 6.1.1 fluid leakage testing.'
  },
  'ISO20-F.1': {
    worstCaseReasonEn: 'Universal tensile testing machine setup for axial pull load separation tests.',
    descriptionEn: 'ISO 80369-20 Figure F.1: Apparatus setup for resistance to separation from axial load, showing axial alignment grips and load cell.'
  },
  'ISO20-G.1': {
    worstCaseReasonEn: 'Torsional test bench setup for unscrewing torque evaluation.',
    descriptionEn: 'ISO 80369-20 Figure G.1: Apparatus setup for resistance to separation from unscrewing torque, illustrating torque gauge and rotational drive.'
  },
  'ISO20-H.1': {
    worstCaseReasonEn: 'Overriding torque test bench and collar hoop stress expansion schematic.',
    descriptionEn: 'ISO 80369-20 Figure H.1: Overriding torque test apparatus schematic, showing torque transducer, rotary chuck, and Figure C.3 worst-case reference fixture.'
  },
  'ISO20-J.1': {
    worstCaseReasonEn: 'Dual-axis pre-assembly apparatus concept schematic (Enersol S15A concept).',
    descriptionEn: 'ISO 80369-20 Figure J.1: Biaxial pre-assembly device schematic, simultaneously applying 27.5 N axial push force and 0.12 N·m assembly torque for 5-6 s.'
  },
  'ISO20-K.1': {
    worstCaseReasonEn: 'Aspiration bubble detection test apparatus schematic.',
    descriptionEn: 'ISO 80369-20 Figure K.1: Submersion aspiration apparatus layout, showing transparent water bath, vacuum aspirating syringe, and illumination source.'
  }
};

export const TERM_DICTIONARY_EN: Record<string, string> = {
  // Application Domains & Anatomical Classifications
  '血管應用 (-7)': 'Vascular App (-7)',
  '腸道應用 (-3)': 'Enteral App (-3)',
  '神經軸 (-6)': 'Neuraxial App (-6)',
  '防呆互斥矩陣 Lockout': 'Lockout Matrix',
  '非通用介面，100% 避免跨應用誤接': 'Non-interchangeable interface preventing misconnections',
  '預防靜脈藥物誤注入脊髓或腸胃道': 'Preventing IV Drug Misconnection into Spine/Enteral',
  '3D CAD 碰撞分析 & 實體強制互接測試': '3D CAD Collision Analysis & Physical Lockout Mating',
  '3D CAD 防干涉評估 (Annex D)': '3D CAD Clearance Evaluation (Annex D)',

  // Geometric Dimensions & Features
  '錐體長度 e': 'Cone Length e',
  '小端直徑 Ød': 'Small End Ød',
  '大端直徑 Øg': 'Large End Øg',
  '大端內徑 ØD': 'Large ID ØD',
  '小端內徑 ØG': 'Small ID ØG',
  '公錐小端直徑 Ød': 'Small End Diameter Ød',
  '最小配合長度 Min Length': 'Min Engagement Length',
  '圓錐斜率 Taper Ratio': 'Taper Ratio (6%)',
  '錐度斜率 Taper Angle': 'Taper Angle (1°43\'9")',
  '錐度 (Taper)': '6% Taper',
  '6% 內錐面': '6% Internal Cone',
  '6% Luer 標稱錐度': '6% Luer Nominal Taper',
  'NRFit 20% 大錐度': 'NRFit 20% Steep Taper',
  'ENFit 反向鎖定結構': 'ENFit Reverse Lock Geometry',
  '螺距 Pitch': 'Thread Pitch (2.5 mm)',
  '外螺紋 (Thread)': 'External Thread',
  '螺紋特徵': 'Thread Characteristics',
  '螺紋結構': 'Thread Structure',
  '投影量 c': 'Projection c',
  '牙型角度': 'Thread Flank Angle',
  '25° (雙線螺紋)': '25° (Double-start Thread)',
  '360° 全周螺紋': '360° Continuous Full Thread',
  '標稱全螺紋/雙線螺紋': 'Nominal Full / Double-start Thread',
  '最壞情況極限牙型': 'Worst-case Limit Thread Profile',
  '套環結構': 'Collar Structure',
  '獨立 360° 旋轉套環': 'Independent 360° Swivel Collar',
  '防管路扭曲 (Anti-Torsion)': 'Anti-torsion Tubing Protection',
  '主要功能': 'Main Function',
  '耳翼寬度': 'Lug Width',
  '背側角度': 'Flank Angle',
  '耳翼樣態': 'Lug Profile',
  '包絡直徑': 'Envelope Diameter',
  'Ø7.80 mm (最大外界)': 'Ø7.80 mm (Max Envelope)',
  'Variant A 直角耳翼': 'Variant A Right-angled Lug',
  '耳翼寬度 (Tab Width)': 'Lug Width (Tab Width)',
  '背側角度 (Flank Angle)': 'Flank Angle (30°)',
  '標準耳翼寬度 Tab Width': 'Standard Lug Width',
  '標稱母耳翼 C.1 Tab Width': 'Nominal Lug Width (C.1 3.50mm)',
  '極限母耳翼 C.3 Tab Width': 'Worst-Case Lug Width (C.3 2.71mm)',
  '3.50 (C.1 標稱)': '3.50 mm (C.1 Nominal)',
  '3.50 mm (標稱)': '3.50 mm (Nominal)',
  '2.71 (縮窄 22%)': '2.71 mm (-22% narrowed)',
  '2.71 mm (縮窄 22%)': '2.71 mm (-22% narrowed)',
  '30° (外撐力更大)': '30° (higher outward hoop force)',
  '僅 2 顆對稱耳翼 ("ears")': '2 symmetric lugs ("ears")',
  '特徵結構': 'Structural Features',
  '用途': 'Application Scope',

  // Connector Gender & Types
  '適用類型': 'Applies To',
  '適用受測物': 'Applies To',
  '母滑動 (Female Slip)': 'Female Slip',
  '公滑動 (Male Slip)': 'Male Slip',
  '母鎖定 (Female Lock)': 'Female Lock',
  '公鎖定 (Male Lock)': 'Male Lock',
  '母魯爾鎖定 (Female Lock)': 'Female Luer Lock',
  '公魯爾鎖定 (Male Lock)': 'Male Luer Lock',
  '母魯爾滑動 (Female Slip)': 'Female Luer Slip',
  '公魯爾滑動 (Male Slip)': 'Male Luer Slip',
  '母魯爾鎖定': 'Female Luer Lock',
  '公魯爾鎖定': 'Male Luer Lock',
  '母魯爾滑動': 'Female Luer Slip',
  '公魯爾滑動': 'Male Luer Slip',
  '公金屬件': 'Male Metal Fixture',
  '母金屬件': 'Female Metal Fixture',

  // Reference Fixtures & Materials
  '最壞夾具': 'Worst-Case Fixture',
  '最壞情況夾具': 'Worst-Case Fixture',
  '極限夾具 Critical Fixture': 'Critical Fixture',
  'Fig.C.3 (2.71mm 耳翼)': 'Fig. C.3 (2.71mm narrow lug)',
  '材質要求 Material': 'Material Requirement',
  '表面粗糙度 Surface Finish': 'Surface Roughness (Ra ≤ 0.8 µm)',
  '表面粗糙度': 'Surface Roughness (Ra)',
  'ISO: 硬化不鏽鋼(抗磨損) / 17-4PH(≥45HRC)或316(須表面氮化)': 'Hardened Stainless Steel (17-4PH ≥45 HRC / Nitrided 316)',

  // Quantitative Test Parameters & Conditions
  '裝配扭矩 Assembly Torque': 'Assembly Torque',
  '標準裝配扭矩 Assembly Torque': 'Assembly Torque',
  '預裝配扭矩 Assembly Torque': 'Pre-assembly Torque',
  '預裝配扭矩': 'Pre-assembly Torque',
  '預裝配軸向力 Axial Force': 'Pre-assembly Axial Force',
  '裝配軸向推力 Axial Force': 'Axial Assembly Force',
  '預裝配軸推力': 'Pre-assembly Push Force',
  '預裝配推力': 'Pre-assembly Push Force',
  '預裝配時間 Hold Time': 'Pre-assembly Hold Time',
  '裝配保持時間 Hold Time': 'Assembly Hold Time',
  '保持時間 Hold Time': 'Hold Time',
  '持壓時間 Hold Time': 'Hold Time',
  '持壓時間': 'Hold Time',
  '保持時間': 'Hold Time',
  '測試靜置時間 Duration': 'Conditioning Duration',
  '靜置時間 Conditioning Time': 'Conditioning Duration',
  '靜置時間': 'Conditioning Duration',
  '測試壓力 Test Pressure': 'Test Pressure',
  '測試壓力': 'Test Pressure',
  '感測器精度': 'Sensor Accuracy',
  '氣壓降極限 Max Leak Rate': 'Max Leak Rate Limit',
  '氣壓壓降極限 Max Leak Rate': 'Max Leak Rate Limit',
  '洩漏極限 Max Leak Rate': 'Max Leak Rate Limit',
  '洩漏極限': 'Leak Rate Limit',
  '負壓極限 Test Vacuum': 'Test Vacuum',
  '負壓範圍': 'Vacuum Range',
  '真空負壓 Test Vacuum': 'Test Vacuum',
  '水滴法持壓 Hold Time': 'Falling Drop Hold Time',
  '壓降法持壓 Hold Time': 'Pressure Decay Hold Time',
  '破壞扭矩 Over-torque': 'Breaking Over-torque',
  '過載扭矩': 'Over-torque',
  '測試扭矩 Test Torque': 'Test Torque',
  '伺服轉速': 'Rotational Speed',
  '軸向拉力 Pull Force': 'Axial Pull Force',
  '鎖定型軸向力 Lock Force': 'Lock Axial Pull Force',
  '滑動型軸向力 Slip Force': 'Slip Axial Pull Force',
  'Lock 測試拉力': 'Lock Pull Force (32–35 N)',
  'Slip 測試拉力': 'Slip Pull Force (23–25 N)',
  '預旋扭矩 Pre-Torque': 'Pre-Torque',
  '反向扭矩 Reverse Torque': 'Reverse Torque',
  '反向扭矩 Unscrewing Torque': 'Unscrewing Torque',
  'Annex G 反旋力': 'Annex G Unscrewing Torque',
  'Annex I 拆卸峰值': 'Annex I Peak Removal Force',
  '物理機制 Physics': 'Physical Mechanism',
  '失敗模式 Failure Mode': 'Failure Mode',
  '機構系統 Mechanism': 'Mechanical Mechanism',
  '適用標準 Target Standard': 'Target Standard',
  '防錯設計 Misconnection Proof': 'Misconnection Proofing',
  '風險管制 Safety Risk': 'Safety Risk Control',
  '引用規範 References': 'Normative References',
  '核心術語 Core Terms': 'Core Terms',
  '統計方法 Method': 'Statistical Method',
  '常態性測試 Normality Test': 'Normality Test',
  '容許限 UTL/LTL': 'Tolerance Limit (UTL/LTL)',
  '變量容差限度 UTL/LTL': 'Tolerance Limit (UTL/LTL)',
  'k 係數 k-Factor': 'k-Factor',
  '最小樣本數 Min n': 'Minimum Sample Size n',
  '置信水準 / 遵從率 95/95': 'Confidence / Conformance (95/95)',
  '原理附錄 Rationale Annex': 'Rationale Annex',
  '評估附錄 Assessment Annex': 'Assessment Annex',
  '測試矩陣 Summary Matrix': 'Summary Matrix',
  '測試方法': 'Test Method',
  '合格標準': 'Acceptance Criteria',
  '試驗條件': 'Test Conditions',
  '試驗環境 Ambient Environment': 'Ambient Environment',
  '靜置環境 Environment': 'Conditioning Environment',
  '環境溫度 Temperature': 'Ambient Temperature',
  '環境溫度': 'Ambient Temperature',
  '測試介質': 'Test Medium',
  '檢測基準': 'Inspection Criteria',
  '預處理環境 Preconditioning (ISO 80369-20)': 'Preconditioning (ISO 80369-20)',
  '測試執行環境 Test Environment': 'Test Environment',
  '法規效力': 'Regulatory Validity',

  // Failure & Physical Descriptions
  '環向應力膨脹 (Hoop Expansion) 滑脫': 'Hoop Expansion Overriding Failure',
  '6% 錐面摩擦自鎖力 (Self-locking taper)': '6% Cone Friction Self-Locking Force',
  '23°C 空氣靜置 48h (ISO標準)': '23°C Air Conditioning 48 h (ISO Annex E)',
  '23°C 空氣 48h (ISO標準)': '23°C Air Conditioning 48 h (ISO Annex E)',
  '雙軸線性導軌重錘與定扭矩盤 (S15A 原理)': 'Biaxial Linear Guide Deadweight & Torque Disk (S15A)',
  '容許限分析 (Tolerance Limit Analysis)': 'Tolerance Limit Analysis (UTL/LTL)',
  '必須先驗證數據符合常態分佈（如 Shapiro-Wilk）': 'Verify data follows normal distribution (e.g. Shapiro-Wilk)',
  '單側公差上限 (Upper Tolerance Limit)': 'Upper Tolerance Limit (UTL)',
  '依樣本數 n 與信心水準 (95%/99%) 查表決定': 'Determined via table lookup for sample size n & confidence level (95%/99%)',
  '建議 n ≥ 30（提供足夠統計功效）': 'Recommended n ≥ 30 for sufficient statistical power',
  '無水滴擴散': 'Zero droplet formation or dripping',
  '水下沉浸目視氣泡法': 'Submerged Visual Bubble Method',
  '無連續產生氣泡流': 'No continuous bubble stream',
  '❌ 不被 FDA / TFDA 認可': '❌ Not accepted by FDA / TFDA',

  // Stages & Chronological Values
  '1. 充氣 (Fill)': '1. Fill Phase',
  '2. 穩定 (Stabilize)': '2. Stabilize Phase',
  '3. 測試 (Test)': '3. Test Phase',
  '4. 排氣 (Exhaust)': '4. Exhaust Phase',
  '0 ~ 5 秒 (對應 Annex B.4 c 施加壓力)': '0 – 5 s (Pressurization per Annex B.4 c)',
  '5 ~ 15 秒 (隔離氣源熱平衡與蠕變穩定)': '5 – 15 s (Thermal equilibrium & stabilization)',
  '15 ~ 35 秒 (對應 Annex B.4 d/e 量測 ΔP)': '15 – 35 s (ΔP differential measurement per Annex B.4 d/e)',
  '35 秒後 (測試結束釋放壓力)': 'After 35 s (Test complete, exhaust pressure)',
  '15 ~ 20 秒': '15 – 20 s',
  '30 ~ 35 秒': '30 – 35 s',
  '5 ~ 6 秒': '5 – 6 s',
  '5 - 6 秒': '5 – 6 s',
  '≥ 48 小時': '≥ 48 h',
  '32 ~ 35 N (10-15秒)': '32 – 35 N (10–15 s)',
  '23 ~ 25 N (10-15秒)': '23 – 25 N (10–15 s)',
  '0.02 N·m (持壓 10s)': '0.02 N·m (hold 10 s)',
  '靜置 10~15 分鐘後量測': 'Measure after 10–15 min relaxation',
  '去離子水 (De-aerated Water)': 'De-aerated Distilled Water',
  'Annex A (幾何量測法)': 'Annex A (Geometric Measurement)',

  // Units & Basic Modifiers
  '秒': 's',
  '小時': 'h',
  '分': 'min'
};

export const getTopicShortSummary = (topic: any, isEn: boolean): string => {
  if (!topic) return '';
  if (!isEn) return topic.shortSummaryZh || '';
  if (topic.shortSummaryEn) return topic.shortSummaryEn;
  return TOPIC_I18N[topic.id]?.shortSummaryEn || topic.shortSummaryZh || '';
};

export const getTopicDetailedDescription = (topic: any, isEn: boolean): string => {
  if (!topic) return '';
  if (!isEn) return topic.detailedDescriptionZh || '';
  if (topic.detailedDescriptionEn) return topic.detailedDescriptionEn;
  return TOPIC_I18N[topic.id]?.detailedDescriptionEn || topic.detailedDescriptionZh || '';
};

export const getTopicEngineeringRisk = (topic: any, isEn: boolean): string => {
  if (!topic) return '';
  if (!isEn) return topic.engineeringRiskZh || '';
  if (topic.engineeringRiskEn) return topic.engineeringRiskEn;
  return TOPIC_I18N[topic.id]?.engineeringRiskEn || topic.engineeringRiskZh || '';
};

export const getTopicAuditFocus = (topic: any, isEn: boolean): string => {
  if (!topic) return '';
  if (!isEn) return topic.auditFocusZh || '';
  if (topic.auditFocusEn) return topic.auditFocusEn;
  return TOPIC_I18N[topic.id]?.auditFocusEn || topic.auditFocusZh || '';
};

export const getClauseObjective = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.objectiveZh || '';
  if (clause.objectiveEn) return clause.objectiveEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.objectiveEn || clause.objectiveZh || '';
};

export const getClauseAppliesTo = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.appliesToZh || '';
  if (clause.appliesToEn) return clause.appliesToEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.appliesToEn || clause.appliesToZh || '';
};

export const getClauseTitle = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.titleZh || '';
  if (clause.titleEn) return clause.titleEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.titleEn || clause.titleZh || '';
};

export const getClauseType = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.typeZh || '';
  if (clause.typeEn) return clause.typeEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.typeEn || (clause.standard?.includes('80369-20') ? 'Test Method' : 'Requirement');
};

export const getClauseRegulatoryTip = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.regulatoryTipZh || '';
  if (clause.regulatoryTipEn) return clause.regulatoryTipEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.regulatoryTipEn || clause.regulatoryTipZh || '';
};

export const getClauseFixture = (clause: any, isEn: boolean): string => {
  if (!clause) return '';
  if (!isEn) return clause.fixtureRequiredZh || '';
  if (clause.fixtureRequiredEn) return clause.fixtureRequiredEn;
  const id = clause.id || '';
  return CLAUSE_I18N[id]?.fixtureRequiredEn || clause.fixtureRequiredZh || '';
};

export const getFigureWorstCaseReason = (fig: any, isEn: boolean): string => {
  if (!fig) return '';
  if (!isEn) return fig.worstCaseReasonZh || '';
  if (fig.worstCaseReasonEn) return fig.worstCaseReasonEn;
  const id = fig.id || '';
  return FIGURE_I18N[id]?.worstCaseReasonEn || fig.worstCaseReasonZh || '';
};

export const getFigureDescription = (fig: any, isEn: boolean): string => {
  if (!fig) return '';
  if (!isEn) return fig.descriptionZh || fig.description || '';
  if (fig.descriptionEn) return fig.descriptionEn;
  if (fig.description && fig.description !== fig.descriptionZh) return fig.description;
  const id = fig.id || '';
  return FIGURE_I18N[id]?.descriptionEn || fig.descriptionZh || '';
};

/**
 * Universal text translator with comprehensive dictionary lookup and intelligent CJK extraction fallbacks.
 */
export const translateHighlightText = (text: string, isEn: boolean): string => {
  if (!text) return '';
  if (!isEn) return text;
  
  const trimmed = text.trim();
  if (TERM_DICTIONARY_EN[trimmed]) {
    return TERM_DICTIONARY_EN[trimmed];
  }

  // Check if string contains CJK
  const cjkRegex = /[\u4e00-\u9fff]/;
  if (!cjkRegex.test(trimmed)) {
    return trimmed;
  }

  // Fallback 1: Extract English substring from parentheses e.g. "公魯爾鎖定 (Male Lock)" -> "Male Lock"
  const parenMatch = trimmed.match(/\(([A-Za-z0-9\s.,'°%≥≤·\-–/±]+)\)/);
  if (parenMatch && parenMatch[1] && !cjkRegex.test(parenMatch[1])) {
    return parenMatch[1].trim();
  }

  // Fallback 2: Extract trailing English text after Chinese e.g. "裝配扭矩 Assembly Torque" -> "Assembly Torque"
  const trailingEnMatch = trimmed.match(/[\u4e00-\u9fff]+\s+([A-Za-z0-9\s()·.\-–/±%≥≤]+)$/);
  if (trailingEnMatch && trailingEnMatch[1] && !cjkRegex.test(trailingEnMatch[1])) {
    return trailingEnMatch[1].trim();
  }

  // Fallback 3: Common substring replacements
  let replaced = trimmed
    .replace(/秒/g, ' s')
    .replace(/小時/g, ' h')
    .replace(/分鐘/g, ' min')
    .replace(/（/g, '(')
    .replace(/）/g, ')')
    .replace(/推力/g, 'Axial Force')
    .replace(/拉力/g, 'Pull Force')
    .replace(/扭矩/g, 'Torque')
    .replace(/真空/g, 'Vacuum')
    .replace(/負壓/g, 'Vacuum')
    .replace(/水壓法/g, 'Hydraulic')
    .replace(/氣壓法/g, 'Pressure Decay')
    .replace(/水或空氣/g, 'Water or Air')
    .replace(/預處理/g, 'Preconditioning')
    .replace(/測試執行/g, 'Test')
    .replace(/相對濕度/g, 'Relative Humidity')
    .replace(/環境溫度/g, 'Ambient Temp')
    .replace(/持壓/g, 'Hold')
    .replace(/保持/g, 'Hold')
    .replace(/標準/g, 'Standard');

  // Strip remaining solitary CJK characters if meaningful English exists
  if (/[A-Za-z0-9]/.test(replaced)) {
    replaced = replaced.replace(/[\u4e00-\u9fff]+/g, '').trim();
  }

  return replaced || trimmed;
};

/**
 * Translates quantitative conditions strings (temperature, pressure, hold time, media) into English.
 */
export const translateQuantitativeCondition = (text?: string, isEn?: boolean): string => {
  if (!text) return '';
  if (!isEn) return text;

  const trimmed = text.trim();
  if (TERM_DICTIONARY_EN[trimmed]) return TERM_DICTIONARY_EN[trimmed];

  const cjkRegex = /[\u4e00-\u9fff]/;
  if (!cjkRegex.test(trimmed)) return trimmed;

  // Specific common patterns
  if (trimmed.includes('50 N') && trimmed.includes('推力')) return '50 N (Impact Push Force)';
  if (trimmed.includes('預處理') && trimmed.includes('20 ± 5') && trimmed.includes('15°C – 30°C')) {
    return 'Preconditioning: (20 ± 5)°C / Test: 15°C – 30°C (ISO 80369-20 Clause 4)';
  }
  if (trimmed.includes('≥ 24 小時')) return '≥ 24 h (Preconditioning)';
  if (trimmed.includes('相對濕度 RH')) {
    return 'RH: Preconditioning (50 ± 10)% / Test 10% – 70%';
  }
  if (trimmed.includes('水滴法') && trimmed.includes('壓降法')) {
    return '30–35 s (Hydraulic) / 15–20 s (Pneumatic)';
  }
  if (trimmed === '水或空氣') return 'Water or Air';
  if (trimmed.includes('蒸餾水') || trimmed.includes('亞甲藍')) {
    return 'Distilled / potable water (methylene blue dye optional)';
  }
  if (trimmed.includes('80.0') && trimmed.includes('真空負壓')) {
    return '80.0–88.0 kPa (Vacuum)';
  }
  if (trimmed.includes('80.0') && trimmed.includes('負壓')) {
    return '80.0–88.0 kPa (Vacuum)';
  }
  if (trimmed.includes('指定測試時間')) return 'Designated test duration';
  if (trimmed.includes('透明水容器')) return 'Transparent water vessel (~1/3 filled)';
  if (trimmed.includes('0.15 - 0.17 N·m') && trimmed.includes('目標')) {
    return '0.15–0.17 N·m (Target 0.16 N·m)';
  }
  if (trimmed.includes('0.018') && trimmed.includes('反向')) {
    return '0.018–0.020 N·m (Reverse)';
  }
  if (trimmed.includes('10 - 15 分鐘') && trimmed.includes('靜置')) {
    return '10–15 min (Relaxation)';
  }
  if (trimmed.includes('按產品規格上限')) {
    return 'Per product specification upper limit (e.g. ≤ 0.24 N·m)';
  }
  if (trimmed.includes('23°C') && trimmed.includes('Annex E')) {
    return '23°C controlled air environment (ISO 80369-20 Annex E)';
  }
  if (trimmed.includes('20°C ± 2°C') && trimmed.includes('標準計量')) {
    return '20°C ± 2°C (Standard Metrology Room)';
  }
  if (trimmed.includes('26.5 - 27.5 N') && trimmed.includes('軸向推力')) {
    return '26.5–27.5 N (Axial Push Force)';
  }
  if (trimmed.includes('30 - 35 秒')) return '30–35 s';
  if (trimmed.includes('15 - 20 秒') || trimmed.includes('15 秒 - 20 秒')) return '15–20 s';
  if (trimmed.includes('10 - 15 秒') || trimmed.includes('10 秒 - 15 秒')) return '10–15 s';
  if (trimmed.includes('5 - 10 秒') || trimmed.includes('5 秒 - 10 秒')) return '5–10 s';
  if (trimmed.includes('5 - 6 秒')) return '5–6 s';

  return translateHighlightText(trimmed, true);
};

/**
 * Returns English or Chinese test procedure steps for any clause.
 */
export const getClauseTestProcedureSteps = (clause: any, isEn: boolean): string[] => {
  if (!clause) return [];
  if (!isEn) return clause.testProcedureStepsZh || [];
  if (clause.testProcedureStepsEn && clause.testProcedureStepsEn.length > 0) {
    return clause.testProcedureStepsEn;
  }

  // Standard step templates for well-known ISO clauses
  const id = clause.id || '';
  if (id === 'iso7-6.1' || id === '6.1') {
    return [
      'Condition connector at (20 ± 5) °C and (50 ± 10) % RH for not less than 24 h (ISO 80369-20 Clause 4).',
      'Pre-assemble connector to reference connector simultaneously applying 0.08–0.12 N·m torque and 26.5–27.5 N axial push for 5–6 s, then release all loads.',
      'Connect assembled test specimen to pressure test apparatus and purge internal air (hydraulic) or connect to dry pneumatic circuit with known system volume V.',
      'Apply (300 to 330) kPa test pressure and maintain for designated hold time: 30–35 s for hydraulic falling drop or 15–20 s for pneumatic pressure decay.',
      'Inspect for falling drop of liquid or record differential pressure change ΔP and verify compliance with acceptance criteria.'
    ];
  }
  if (id === 'iso7-6.2' || id === '6.2') {
    return [
      'Condition test connectors at standard laboratory atmosphere for not less than 24 h.',
      'Pre-assemble connector to standard reference connector applying 0.08–0.12 N·m torque and 26.5–27.5 N axial force for 5–6 s, then release.',
      'Connect specimen to vacuum decay test system (Annex D) or submersion aspiration apparatus (Annex K).',
      'Draw sub-atmospheric vacuum of (80.0 to 88.0) kPa and maintain for 15–20 s.',
      'Record vacuum decay rate ΔP or visually inspect for continuous bubble stream over 15–20 s.'
    ];
  }
  if (id === 'iso7-6.3' || id === '6.3') {
    return [
      'Pre-assemble polymer connector to metal reference connector applying standard torque (0.08–0.12 N·m) and axial force (26.5–27.5 N) for 5–6 s.',
      'Place assembled connector in environmental chamber maintained at (23 ± 2) °C in air for not less than 48 h per ISO 80369-20 Annex E.',
      'Immediately following 48 h conditioning, examine under optical magnification for micro-cracks.',
      'Subject assembled connection directly to Clause 6.1 leakage test at 300–330 kPa and verify compliance.'
    ];
  }
  if (id === 'iso7-6.4' || id === '6.4') {
    return [
      'Pre-assemble connector to designated worst-case reference connector (Figure C.3 for male lock, Figure C.6 for female lock) per Annex H.4.',
      'Mount assembled specimen in universal tensile testing machine using self-aligning grips.',
      'Apply axial pull force at a rate not exceeding 10 N/s until reaching specified challenge load: 23–25 N for slip connectors or 32–35 N for lock connectors.',
      'Maintain peak axial pull load for 10–15 s.',
      'Verify that connector remains completely assembled without separating from reference connector.'
    ];
  }
  if (id === 'iso7-6.5' || id === '6.5') {
    return [
      'Pre-assemble Luer lock connector to standard reference connector per standard procedure and allow 10–15 min rest.',
      'Mount specimen in low-torque torsional test bench with axis strictly aligned.',
      'Apply reverse (unscrewing) torque of 0.018 to 0.020 N·m at a rate not exceeding 0.1 rad/s.',
      'Maintain reverse unscrewing torque for 10–15 s.',
      'Verify that threaded connection remains engaged without unscrewing or separating.'
    ];
  }
  if (id === 'iso7-6.6' || id === '6.6') {
    return [
      'Mandatory pre-assembly: simultaneously apply 0.08–0.12 N·m torque and 26.5–27.5 N axial push for 5–6 s to Figure C.3 worst-case reference connector, then release (Annex H.4 a).',
      'Mount assembly into rotary torque testing bench.',
      'Apply destructive overriding torque continuously at ≤ 0.1 rad/s until reaching 0.15 to 0.17 N·m.',
      'Maintain (0.15 to 0.17) N·m torque for 5 to 10 s.',
      'Verify that lugs/threads do not override or strip, and verify that connector shows no cocking (Annex H.4 d).'
    ];
  }

  // Fallback: translate steps if available
  if (clause.testProcedureStepsZh && clause.testProcedureStepsZh.length > 0) {
    return clause.testProcedureStepsZh.map((step: string) => translateHighlightText(step, true));
  }

  return ['Follow standard protocol per ISO 80369-20 test clause methodology.'];
};

/**
 * Returns English or Chinese acceptance criteria for any clause.
 */
export const getClauseAcceptanceCriteria = (clause: any, isEn: boolean): string[] => {
  if (!clause) return [];
  if (!isEn) return clause.acceptanceCriteriaZh || [];
  if (clause.acceptanceCriteriaEn && clause.acceptanceCriteriaEn.length > 0) {
    return clause.acceptanceCriteriaEn;
  }

  const id = clause.id || '';
  if (id === 'iso7-6.1' || id === '6.1') {
    return [
      'Hydraulic method (6.1.3): No falling drop of water formed or released over (30 to 35) s at (300 to 330) kPa.',
      'Pneumatic pressure decay (6.1.2): Maximum leakage rate shall not exceed 0.005 Pa·m³/s over (15 to 20) s at (300 to 330) kPa.',
      'Either hydraulic or pneumatic method may be used; passing either satisfies ISO 80369-7 6.1.1 requirements.'
    ];
  }
  if (id === 'iso7-6.2' || id === '6.2') {
    return [
      'Vacuum decay method (Annex D): Maximum leakage rate shall not exceed 0.005 Pa·m³/s over (15 to 20) s at (80.0 to 88.0) kPa negative pressure.',
      'Submersion aspiration method (Annex K): No continuous stream of air bubbles observed during (15 to 20) s hold.'
    ];
  }
  if (id === 'iso7-6.3' || id === '6.3') {
    return [
      'Statutory Acceptance: Shall meet the requirements of Clause 6.1.1 (positive-pressure fluid leakage at 300 to 330 kPa) after 48 h assembly hold.',
      'Engineering Observation: No evidence of stress cracking, crazing, or burst failure on visual inspection.'
    ];
  }
  if (id === 'iso7-6.4' || id === '6.4') {
    return [
      'Slip connectors: Shall not separate from reference connector under 23 N to 25 N axial force for (10 to 15) s.',
      'Lock connectors: Shall not separate from Figure C.3 reference connector under 32 N to 35 N axial force for (10 to 15) s.'
    ];
  }
  if (id === 'iso7-6.5' || id === '6.5') {
    return [
      'Shall remain fully engaged without unscrewing or separating under (0.018 to 0.020) N·m reverse torque for (10 to 15) s.'
    ];
  }
  if (id === 'iso7-6.6' || id === '6.6') {
    return [
      'Threads and lugs shall not override the threads or lugs of Figure C.3 reference connector under (0.15 to 0.17) N·m torque for (5 to 10) s.',
      'No cocking of the connector relative to reference connector shall occur (ISO 80369-20 Annex H.4 d).'
    ];
  }
  if (id === 'iso7-clause-5' || id === 'iso7-clause-5.1') {
    return [
      'Dimensions shall conform fully to ISO 80369-7 Annex B engineering drawings (Figures B.1 through B.6).',
      'Conical fitting shall have a nominal 6% (1:16.667) taper ratio with cone angle 1°43\'9".'
    ];
  }
  if (id === 'iso7-clause-4') {
    return [
      'Connector shall not physically connect or cross-mate with small-bore connectors from other medical application standards (ISO 80369-1 Annex B).'
    ];
  }

  // Fallback: translate criteria items
  if (clause.acceptanceCriteriaZh && clause.acceptanceCriteriaZh.length > 0) {
    return clause.acceptanceCriteriaZh.map((crit: string) => translateHighlightText(crit, true));
  }

  return ['Must comply with acceptance limits specified in the applicable ISO standard clause.'];
};

export const formatUnit = (unit?: string, isEn?: boolean): string => {
  if (!unit) return '';
  if (!isEn) return unit;
  if (unit === '秒') return 's';
  if (unit === '小時') return 'h';
  if (unit === '分') return 'min';
  return unit;
};

